//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIAEKtool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIAEKtool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document&gt;
        ///  &lt;Engineering version=&quot;V15&quot; /&gt;
        ///  &lt;DocumentInfo&gt;
        ///   
        ///  &lt;/DocumentInfo&gt;
        ///  &lt;SW.Blocks.GlobalDB ID=&quot;0&quot;&gt;
        ///    &lt;AttributeList&gt;
        ///      &lt;AutoNumber&gt;true&lt;/AutoNumber&gt;
        ///      &lt;HeaderAuthor /&gt;
        ///      &lt;HeaderFamily /&gt;
        ///      &lt;HeaderName /&gt;
        ///      &lt;HeaderVersion&gt;0.1&lt;/HeaderVersion&gt;
        ///      &lt;Interface&gt;
        ///        &lt;Sections xmlns=&quot;http://www.siemens.com/automation/Openness/SW/Interface/v3&quot;&gt;
        ///          &lt;Section Name=&quot;Static&quot;&gt;
        ///          &lt;/Section&gt;
        ///        &lt;/Sections&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialPresetDB {
            get {
                return ResourceManager.GetString("InitialPresetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Document&gt;
        ///  &lt;Engineering version=&quot;V15&quot; /&gt;
        ///  &lt;DocumentInfo&gt;
        ///  &lt;/DocumentInfo&gt;
        ///  &lt;SW.Blocks.FC ID=&quot;0&quot;&gt;
        ///    &lt;AttributeList&gt;
        ///      &lt;AutoNumber&gt;true&lt;/AutoNumber&gt;
        ///      &lt;HeaderAuthor /&gt;
        ///      &lt;HeaderFamily /&gt;
        ///      &lt;HeaderName /&gt;
        ///      &lt;HeaderVersion&gt;0.1&lt;/HeaderVersion&gt;
        ///      &lt;Interface&gt;&lt;Sections xmlns=&quot;http://www.siemens.com/automation/Openness/SW/Interface/v3&quot;&gt;
        ///  &lt;Section Name=&quot;Input&quot;&gt;
        ///    &lt;Member Name=&quot;Index&quot; Datatype=&quot;Int&quot; Accessibility=&quot;Public&quot;&gt;&lt;AttributeList&gt;&lt;/AttributeList&gt;&lt;/Member&gt;
        ///  &lt;/Sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialPresetSCL {
            get {
                return ResourceManager.GetString("InitialPresetSCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document&gt;
        ///  &lt;Engineering version=&quot;V15&quot; /&gt;
        ///  &lt;DocumentInfo&gt;
        ///   
        ///  &lt;/DocumentInfo&gt;
        ///  &lt;SW.Types.PlcStruct ID=&quot;0&quot;&gt;
        ///    &lt;AttributeList&gt;
        ///      &lt;Interface&gt;
        ///        &lt;Sections xmlns=&quot;http://www.siemens.com/automation/Openness/SW/Interface/v3&quot;&gt;
        ///          &lt;Section Name=&quot;None&quot;&gt;
        ///          &lt;/Section&gt;
        ///        &lt;/Sections&gt;
        ///      &lt;/Interface&gt;
        ///      &lt;Name&gt;PresetType&lt;/Name&gt;
        ///    &lt;/AttributeList&gt;
        ///    &lt;ObjectList&gt;   
        ///    &lt;/ObjectList&gt;
        ///  &lt;/SW.Types.PlcStruct&gt;
        ///&lt;/Document&gt;.
        /// </summary>
        internal static string InitialPresetType {
            get {
                return ResourceManager.GetString("InitialPresetType", resourceCulture);
            }
        }
    }
}
